# Generated by Django 5.0.4 on 2024-05-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.DurationField(verbose_name='периодичность'),
        ),
    ]
