# Generated by Django 5.0.4 on 2024-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-29 16:45:00', verbose_name='дата создания письма'),
            preserve_default=False,
        ),
    ]
