# Generated by Django 5.0.4 on 2024-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='customers',
            field=models.ManyToManyField(related_name='mailing', to='mailing_app.customers', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата первой отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.DurationField(help_text='в секундах', verbose_name='периодичность'),
        ),
    ]
