# Generated by Django 5.0.4 on 2024-05-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0003_alter_mailing_customers_alter_mailing_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptsend',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='mailing_app.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='statusmailing',
            name='created',
            field=models.BooleanField(default=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='statusmailing',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='mailing_app.mailing', verbose_name='рассылка'),
        ),
    ]
