# Generated by Django 5.0.4 on 2024-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_alter_attemptsend_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptsend',
            name='attempt_status',
            field=models.BooleanField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], default='created', verbose_name='статус попытки'),
        ),
        migrations.DeleteModel(
            name='StatusMailing',
        ),
    ]
