# Generated by Django 5.0.4 on 2024-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0005_alter_attemptsend_attempt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptsend',
            options={'get_latest_by': 'last_attempt_time', 'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AlterField(
            model_name='attemptsend',
            name='attempt_status',
            field=models.CharField(choices=[('Создана', 'created'), ('Завершена', 'completed'), ('Запущена', 'launched')], default='Создана', max_length=50, verbose_name='статус попытки'),
        ),
    ]
