# Generated by Django 5.0.4 on 2024-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0006_alter_attemptsend_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.DurationField(blank=True, help_text='в секундах', null=True, verbose_name='периодичность'),
        ),
    ]
