# Generated by Django 5.0.4 on 2024-06-04 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0008_mailing_status_alter_attemptsend_attempt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptsend',
            options={'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AlterField(
            model_name='attemptsend',
            name='attempt_status',
            field=models.CharField(choices=[('successful', 'Успешно'), ('failed', 'Неудачно')], default='successful', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата первой отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], default='created', max_length=50, verbose_name='статус рассылки'),
        ),
    ]
