# Generated by Django 5.0.4 on 2024-06-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0009_alter_attemptsend_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='datetime',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='attemptsend',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing_app.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Once a Day'), ('weekly', 'Once a Week'), ('monthly', 'Once a Month')], default='daily', max_length=10, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], default='created', max_length=10, verbose_name='статус'),
        ),
    ]
