# Generated by Django 5.0.4 on 2024-06-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0011_alter_attemptsend_attempt_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='unique_client',
            field=models.BooleanField(default=False, verbose_name='уникальный клиент'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь создавши клиента'),
        ),
    ]
