# Generated by Django 5.0.4 on 2024-06-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0012_customers_unique_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='unique_client',
            new_name='unique_clients',
        ),
    ]
