# Generated by Django 5.0.4 on 2024-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0013_rename_unique_client_customers_unique_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена'), ('failed', 'Провалена')], default='launched', max_length=10, verbose_name='статус'),
        ),
    ]
