# Generated by Django 5.0.4 on 2024-06-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0015_mailing_end_time_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Может отключать рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
